// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel discriminator — drives which provider the router selects.
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_EMAIL       Channel = 1
	Channel_CHANNEL_SMS         Channel = 2
	Channel_CHANNEL_PUSH        Channel = 3
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_EMAIL",
		2: "CHANNEL_SMS",
		3: "CHANNEL_PUSH",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_EMAIL":       1,
		"CHANNEL_SMS":         2,
		"CHANNEL_PUSH":        3,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// Priority controls queue ordering and retry budgets.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_CRITICAL    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

// Terminal status of a dispatched notification.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACCEPTED    Status = 1 // Enqueued to Redis successfully.
	Status_STATUS_DELIVERED   Status = 2 // Provider confirmed delivery.
	Status_STATUS_FAILED      Status = 3 // All retries exhausted; moved to DLQ.
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACCEPTED",
		2: "STATUS_DELIVERED",
		3: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACCEPTED":    1,
		"STATUS_DELIVERED":   2,
		"STATUS_FAILED":      3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

type EmailPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyHtml      string                 `protobuf:"bytes,5,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	BodyText      string                 `protobuf:"bytes,6,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"` // Plain-text fallback.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailPayload) Reset() {
	*x = EmailPayload{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailPayload) ProtoMessage() {}

func (x *EmailPayload) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailPayload.ProtoReflect.Descriptor instead.
func (*EmailPayload) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *EmailPayload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EmailPayload) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailPayload) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailPayload) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *EmailPayload) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

type SMSPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSPayload) Reset() {
	*x = SMSPayload{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSPayload) ProtoMessage() {}

func (x *SMSPayload) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSPayload.ProtoReflect.Descriptor instead.
func (*SMSPayload) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SMSPayload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SMSPayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SMSPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PushPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Arbitrary k/v passed to FCM/APNs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPayload) Reset() {
	*x = PushPayload{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPayload) ProtoMessage() {}

func (x *PushPayload) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPayload.ProtoReflect.Descriptor instead.
func (*PushPayload) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *PushPayload) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PushPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushPayload) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-provided idempotency key (UUIDv4).
	IdempotencyKey string   `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Channel        Channel  `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`
	Priority       Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=notification.v1.Priority" json:"priority,omitempty"`
	// Exactly one of these must be set, matching `channel`.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*SendNotificationRequest_Email
	//	*SendNotificationRequest_Sms
	//	*SendNotificationRequest_Push
	Payload isSendNotificationRequest_Payload `protobuf_oneof:"payload"`
	// Optional caller-scoped metadata for tracing / filtering.
	Metadata      map[string]string `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *SendNotificationRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *SendNotificationRequest) GetPayload() isSendNotificationRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendNotificationRequest) GetEmail() *EmailPayload {
	if x != nil {
		if x, ok := x.Payload.(*SendNotificationRequest_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *SendNotificationRequest) GetSms() *SMSPayload {
	if x != nil {
		if x, ok := x.Payload.(*SendNotificationRequest_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *SendNotificationRequest) GetPush() *PushPayload {
	if x != nil {
		if x, ok := x.Payload.(*SendNotificationRequest_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *SendNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isSendNotificationRequest_Payload interface {
	isSendNotificationRequest_Payload()
}

type SendNotificationRequest_Email struct {
	Email *EmailPayload `protobuf:"bytes,10,opt,name=email,proto3,oneof"`
}

type SendNotificationRequest_Sms struct {
	Sms *SMSPayload `protobuf:"bytes,11,opt,name=sms,proto3,oneof"`
}

type SendNotificationRequest_Push struct {
	Push *PushPayload `protobuf:"bytes,12,opt,name=push,proto3,oneof"`
}

func (*SendNotificationRequest_Email) isSendNotificationRequest_Payload() {}

func (*SendNotificationRequest_Sms) isSendNotificationRequest_Payload() {}

func (*SendNotificationRequest_Push) isSendNotificationRequest_Payload() {}

type SendNotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned job ID (UUIDv7, monotonic).
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=notification.v1.Status" json:"status,omitempty"`
	AcceptedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendNotificationResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SendNotificationResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *SendNotificationResponse) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

type BatchSendRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Notifications []*SendNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendRequest) Reset() {
	*x = BatchSendRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendRequest) ProtoMessage() {}

func (x *BatchSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendRequest.ProtoReflect.Descriptor instead.
func (*BatchSendRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *BatchSendRequest) GetNotifications() []*SendNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type BatchSendResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*SendNotificationResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendResponse) Reset() {
	*x = BatchSendResponse{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendResponse) ProtoMessage() {}

func (x *BatchSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendResponse.ProtoReflect.Descriptor instead.
func (*BatchSendResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *BatchSendResponse) GetResults() []*SendNotificationResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type DispatchRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	JobId   string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Channel Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DispatchRequest_Email
	//	*DispatchRequest_Sms
	//	*DispatchRequest_Push
	Payload       isDispatchRequest_Payload `protobuf_oneof:"payload"`
	Attempt       int32                     `protobuf:"varint,20,opt,name=attempt,proto3" json:"attempt,omitempty"` // Current retry attempt (0-indexed).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *DispatchRequest) GetPayload() isDispatchRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchRequest) GetEmail() *EmailPayload {
	if x != nil {
		if x, ok := x.Payload.(*DispatchRequest_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *DispatchRequest) GetSms() *SMSPayload {
	if x != nil {
		if x, ok := x.Payload.(*DispatchRequest_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *DispatchRequest) GetPush() *PushPayload {
	if x != nil {
		if x, ok := x.Payload.(*DispatchRequest_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *DispatchRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type isDispatchRequest_Payload interface {
	isDispatchRequest_Payload()
}

type DispatchRequest_Email struct {
	Email *EmailPayload `protobuf:"bytes,10,opt,name=email,proto3,oneof"`
}

type DispatchRequest_Sms struct {
	Sms *SMSPayload `protobuf:"bytes,11,opt,name=sms,proto3,oneof"`
}

type DispatchRequest_Push struct {
	Push *PushPayload `protobuf:"bytes,12,opt,name=push,proto3,oneof"`
}

func (*DispatchRequest_Email) isDispatchRequest_Payload() {}

func (*DispatchRequest_Sms) isDispatchRequest_Payload() {}

func (*DispatchRequest_Push) isDispatchRequest_Payload() {}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Downstream provider reference ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *DispatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DispatchResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\fEmailPayload\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_html\x18\x05 \x01(\tR\bbodyHtml\x12\x1b\n" +
	"\tbody_text\x18\x06 \x01(\tR\bbodyText\"D\n" +
	"\n" +
	"SMSPayload\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\xcf\x01\n" +
	"\vPushPayload\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12:\n" +
	"\x04data\x18\x04 \x03(\v2&.notification.v1.PushPayload.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x03\n" +
	"\x17SendNotificationRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x19.notification.v1.PriorityR\bpriority\x125\n" +
	"\x05email\x18\n" +
	" \x01(\v2\x1d.notification.v1.EmailPayloadH\x00R\x05email\x12/\n" +
	"\x03sms\x18\v \x01(\v2\x1b.notification.v1.SMSPayloadH\x00R\x03sms\x122\n" +
	"\x04push\x18\f \x01(\v2\x1c.notification.v1.PushPayloadH\x00R\x04push\x12R\n" +
	"\bmetadata\x18\x14 \x03(\v26.notification.v1.SendNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\x9f\x01\n" +
	"\x18SendNotificationResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.notification.v1.StatusR\x06status\x12;\n" +
	"\vaccepted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptedAt\"b\n" +
	"\x10BatchSendRequest\x12N\n" +
	"\rnotifications\x18\x01 \x03(\v2(.notification.v1.SendNotificationRequestR\rnotifications\"X\n" +
	"\x11BatchSendResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).notification.v1.SendNotificationResponseR\aresults\"\x9d\x02\n" +
	"\x0fDispatchRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\x05email\x18\n" +
	" \x01(\v2\x1d.notification.v1.EmailPayloadH\x00R\x05email\x12/\n" +
	"\x03sms\x18\v \x01(\v2\x1b.notification.v1.SMSPayloadH\x00R\x03sms\x122\n" +
	"\x04push\x18\f \x01(\v2\x1c.notification.v1.PushPayloadH\x00R\x04push\x12\x18\n" +
	"\aattempt\x18\x14 \x01(\x05R\aattemptB\t\n" +
	"\apayload\"r\n" +
	"\x10DispatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId*X\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x01\x12\x0f\n" +
	"\vCHANNEL_SMS\x10\x02\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x03*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04*^\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\x01\x12\x14\n" +
	"\x10STATUS_DELIVERED\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x032\xc2\x01\n" +
	"\x0fNotificationAPI\x12[\n" +
	"\x04Send\x12(.notification.v1.SendNotificationRequest\x1a).notification.v1.SendNotificationResponse\x12R\n" +
	"\tBatchSend\x12!.notification.v1.BatchSendRequest\x1a\".notification.v1.BatchSendResponse2e\n" +
	"\x12NotificationRouter\x12O\n" +
	"\bDispatch\x12 .notification.v1.DispatchRequest\x1a!.notification.v1.DispatchResponseB+Z)notification-service/proto/notificationpbb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_notification_proto_goTypes = []any{
	(Channel)(0),                     // 0: notification.v1.Channel
	(Priority)(0),                    // 1: notification.v1.Priority
	(Status)(0),                      // 2: notification.v1.Status
	(*EmailPayload)(nil),             // 3: notification.v1.EmailPayload
	(*SMSPayload)(nil),               // 4: notification.v1.SMSPayload
	(*PushPayload)(nil),              // 5: notification.v1.PushPayload
	(*SendNotificationRequest)(nil),  // 6: notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 7: notification.v1.SendNotificationResponse
	(*BatchSendRequest)(nil),         // 8: notification.v1.BatchSendRequest
	(*BatchSendResponse)(nil),        // 9: notification.v1.BatchSendResponse
	(*DispatchRequest)(nil),          // 10: notification.v1.DispatchRequest
	(*DispatchResponse)(nil),         // 11: notification.v1.DispatchResponse
	nil,                              // 12: notification.v1.PushPayload.DataEntry
	nil,                              // 13: notification.v1.SendNotificationRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_notification_proto_depIdxs = []int32{
	12, // 0: notification.v1.PushPayload.data:type_name -> notification.v1.PushPayload.DataEntry
	0,  // 1: notification.v1.SendNotificationRequest.channel:type_name -> notification.v1.Channel
	1,  // 2: notification.v1.SendNotificationRequest.priority:type_name -> notification.v1.Priority
	3,  // 3: notification.v1.SendNotificationRequest.email:type_name -> notification.v1.EmailPayload
	4,  // 4: notification.v1.SendNotificationRequest.sms:type_name -> notification.v1.SMSPayload
	5,  // 5: notification.v1.SendNotificationRequest.push:type_name -> notification.v1.PushPayload
	13, // 6: notification.v1.SendNotificationRequest.metadata:type_name -> notification.v1.SendNotificationRequest.MetadataEntry
	2,  // 7: notification.v1.SendNotificationResponse.status:type_name -> notification.v1.Status
	14, // 8: notification.v1.SendNotificationResponse.accepted_at:type_name -> google.protobuf.Timestamp
	6,  // 9: notification.v1.BatchSendRequest.notifications:type_name -> notification.v1.SendNotificationRequest
	7,  // 10: notification.v1.BatchSendResponse.results:type_name -> notification.v1.SendNotificationResponse
	0,  // 11: notification.v1.DispatchRequest.channel:type_name -> notification.v1.Channel
	3,  // 12: notification.v1.DispatchRequest.email:type_name -> notification.v1.EmailPayload
	4,  // 13: notification.v1.DispatchRequest.sms:type_name -> notification.v1.SMSPayload
	5,  // 14: notification.v1.DispatchRequest.push:type_name -> notification.v1.PushPayload
	6,  // 15: notification.v1.NotificationAPI.Send:input_type -> notification.v1.SendNotificationRequest
	8,  // 16: notification.v1.NotificationAPI.BatchSend:input_type -> notification.v1.BatchSendRequest
	10, // 17: notification.v1.NotificationRouter.Dispatch:input_type -> notification.v1.DispatchRequest
	7,  // 18: notification.v1.NotificationAPI.Send:output_type -> notification.v1.SendNotificationResponse
	9,  // 19: notification.v1.NotificationAPI.BatchSend:output_type -> notification.v1.BatchSendResponse
	11, // 20: notification.v1.NotificationRouter.Dispatch:output_type -> notification.v1.DispatchResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_notification_proto_msgTypes[3].OneofWrappers = []any{
		(*SendNotificationRequest_Email)(nil),
		(*SendNotificationRequest_Sms)(nil),
		(*SendNotificationRequest_Push)(nil),
	}
	file_notification_proto_msgTypes[7].OneofWrappers = []any{
		(*DispatchRequest_Email)(nil),
		(*DispatchRequest_Sms)(nil),
		(*DispatchRequest_Push)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
