// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: notification.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationAPI_Send_FullMethodName      = "/notification.v1.NotificationAPI/Send"
	NotificationAPI_BatchSend_FullMethodName = "/notification.v1.NotificationAPI/BatchSend"
)

// NotificationAPIClient is the client API for NotificationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Exposed by api-service (external ingress).
type NotificationAPIClient interface {
	Send(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
	BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*BatchSendResponse, error)
}

type notificationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationAPIClient(cc grpc.ClientConnInterface) NotificationAPIClient {
	return &notificationAPIClient{cc}
}

func (c *notificationAPIClient) Send(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationAPI_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationAPIClient) BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*BatchSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSendResponse)
	err := c.cc.Invoke(ctx, NotificationAPI_BatchSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationAPIServer is the server API for NotificationAPI service.
// All implementations must embed UnimplementedNotificationAPIServer
// for forward compatibility.
//
// Exposed by api-service (external ingress).
type NotificationAPIServer interface {
	Send(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	BatchSend(context.Context, *BatchSendRequest) (*BatchSendResponse, error)
	mustEmbedUnimplementedNotificationAPIServer()
}

// UnimplementedNotificationAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationAPIServer struct{}

func (UnimplementedNotificationAPIServer) Send(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedNotificationAPIServer) BatchSend(context.Context, *BatchSendRequest) (*BatchSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSend not implemented")
}
func (UnimplementedNotificationAPIServer) mustEmbedUnimplementedNotificationAPIServer() {}
func (UnimplementedNotificationAPIServer) testEmbeddedByValue()                         {}

// UnsafeNotificationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationAPIServer will
// result in compilation errors.
type UnsafeNotificationAPIServer interface {
	mustEmbedUnimplementedNotificationAPIServer()
}

func RegisterNotificationAPIServer(s grpc.ServiceRegistrar, srv NotificationAPIServer) {
	// If the following call panics, it indicates UnimplementedNotificationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationAPI_ServiceDesc, srv)
}

func _NotificationAPI_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).Send(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationAPI_BatchSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).BatchSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_BatchSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).BatchSend(ctx, req.(*BatchSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationAPI_ServiceDesc is the grpc.ServiceDesc for NotificationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.NotificationAPI",
	HandlerType: (*NotificationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _NotificationAPI_Send_Handler,
		},
		{
			MethodName: "BatchSend",
			Handler:    _NotificationAPI_BatchSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}

const (
	NotificationRouter_Dispatch_FullMethodName = "/notification.v1.NotificationRouter/Dispatch"
)

// NotificationRouterClient is the client API for NotificationRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Exposed by notification-router (internal, worker → router).
type NotificationRouterClient interface {
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
}

type notificationRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationRouterClient(cc grpc.ClientConnInterface) NotificationRouterClient {
	return &notificationRouterClient{cc}
}

func (c *notificationRouterClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, NotificationRouter_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationRouterServer is the server API for NotificationRouter service.
// All implementations must embed UnimplementedNotificationRouterServer
// for forward compatibility.
//
// Exposed by notification-router (internal, worker → router).
type NotificationRouterServer interface {
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	mustEmbedUnimplementedNotificationRouterServer()
}

// UnimplementedNotificationRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationRouterServer struct{}

func (UnimplementedNotificationRouterServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedNotificationRouterServer) mustEmbedUnimplementedNotificationRouterServer() {}
func (UnimplementedNotificationRouterServer) testEmbeddedByValue()                            {}

// UnsafeNotificationRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationRouterServer will
// result in compilation errors.
type UnsafeNotificationRouterServer interface {
	mustEmbedUnimplementedNotificationRouterServer()
}

func RegisterNotificationRouterServer(s grpc.ServiceRegistrar, srv NotificationRouterServer) {
	// If the following call panics, it indicates UnimplementedNotificationRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationRouter_ServiceDesc, srv)
}

func _NotificationRouter_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationRouterServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationRouter_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationRouterServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationRouter_ServiceDesc is the grpc.ServiceDesc for NotificationRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.NotificationRouter",
	HandlerType: (*NotificationRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _NotificationRouter_Dispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
