apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: router-service
  template:
    metadata:
      labels:
        app: router-service
    spec:
      containers:
      - name: router-service
        image: router-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
          name: grpc
        - containerPort: 8083
          name: metrics
        env:
        - name: NS_GRPC_PORT_ROUTER
          value: "50052"
        - name: NS_METRICS_PORT_ROUTER
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: router-service
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
  - name: metrics
    port: 8083
    targetPort: 8083
